### ISSUE TITLE
Password strength test 

### ISSUE THREAD

**Issue by John-Maravelis** [GeorgeBacky/passwordGenerator#2]
Είδα το post σου στους Έλληνες προγραμματιστές, μπορείς να δοκιμάσεις να βάλεις ένα feature όπου να εισάγεις ένα password και να τσεκάρει το πόσο ισχυρό είναι

**Comment by GeorgeBacky** [comment]
Θα το λαβω στα υποψην μου! Βεβαια θα πρεπει να κανω ενα plan πως θα πρεπει να τοποθετηθεί αυτο το feature , πολυ καλη η ιδέα σου!

**Comment by John-Maravelis** [comment]
Θα μπορούσες να έχεις μια κεντρική οθόνη και 2 buttons για επιλογή και μετά να σε κάνει redirect στο ανάλογο window (form μιας και χρησιμοποιείς C#) ή ένα window χωρισμένο στα 2.

Επίσης, καλό θα ήταν να έχεις καλύτερο documentation αλλά και commenting στον κώδικα σου. 

Δοκίμασε να κάνεις ένα αρχείο .exe από την εφαρμογή σου ώστε να είναι πιο εύκολο ο κόσμος να την τεστάρει!

**Comment by GeorgeBacky** [comment]
Εχω στα releases το Setup.msi για να το κανεις εγκατάσταση
https://github.com/GeorgeBacky/passwordGenerator/releases
